spring:
  datasource:
    url: jdbc:h2:d:\project\KTT\db\name
    username: user
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
